version: '3.8'
services:
  mongo:
    image: mongo
    container_name: storedb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes: 
      - ./mongo_data:/data/db